details:
  namespace: student48-bookinfo-dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  image: ghcr.io/62130500119/bookinfo-details
  tag: dev
ingress:
  host: sitkmutt.bookinfo.dev.opsta.net
  path: "/student48/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2

